const express=require('express');
const router=express.Router();
const patientController=require('../controllers/patientController');
router.post('/register',patientController.registerPatient);
router.post('/login',patientController.loginPatient);
router.get('/:patientId',patientController.getPatientById);
// router.get('/',patientController.getAllPatients);
router.put('/:patientId',patientController.updatePatient);
router.post('/book-appointmen',patientController.bookAppointment);
router.post('/appointments/:patientId',patientController.getAppointments);
router.post('/cancel-appointment/:appointmentId',patientController.cancelAppointment);
router.get('/notifications/:patientId',patientController.getNotifications);
router.post('/notifications/:patientId',patientController.markNotificationsAsSeen);
router.delete('/notifications/:notificationId',patientController.deleteNotification);
module.exports=router;