const express=require('express');
const router=express.Router();
const patientController=require('../controller/patientController');
const auth=require('../middleware/auth');
router.post('/register',patientController.registerPatient);
router.post('/login',patientController.loginPatient);
// router.get('/:patientId',auth.patientAuth,patientController.getPatientById);
// router.get('/',patientController.getAllPatients);
router.put('/',auth.patientAuth,patientController.updatePatient);
router.post('/book-appointment/',auth.patientAuth,patientController.bookAppointment);
router.get('/appointments/',auth.patientAuth,patientController.getPatientAppointments);
router.post('/cancel-appointment/:appointmentId',auth.patientAuth,patientController.cancelAppointment);
router.get('/notifications/:patientId',auth.patientAuth,patientController.getNotifications);
router.post('/notifications/:patientId',auth.patientAuth,patientController.markNotificationAsSeen);
// router.delete('/notifications/:notificationId',patientController.deleteNotification);
module.exports=router;